order = ["Introduction"]


[[classOrder]]
collapsed = false
classes = ["Dec", "VirtualInstance", "Root"]

[[classOrder]]
section = "Observables"
collapsed = false
classes = ["Observable", "State", "Record", "Dict", "Stopwatch", "Timer",
    "Alpha", "Eased", "Spring", "AngleSpring", "IntSpring"]

gitSourceBranch = "main"

[docusaurus]
url = "https://dec.ambergracesoftware.com"
baseUrl = "/"
tagline = "A reactive UI library for Roblox"

[navbar]
title = ""

[navbar.logo]
alt = "Dec"
src = "logo.svg"

[home]
enabled = true
includeReadme = false


[[home.features]]
title = "Feature 1"
description = "This is a feature"
image = "logo.svg"

[[home.features]]
title = "Feature 2"
description = "This is also a feature"
image = "logo.svg"

[footer]
copyright = "Written by Amber Grace. Built with Moonwave and Docusaurus"