[[classOrder]]
section = "Core"
classes = ["Dec", "VirtualInstance", "Root"]

[[classOrder]]
section = "Observables"
classes = ["Observable", "State", "StateRecord", "Stopwatch", "Timer", "Alpha",
    "Eased", "Spring", "AngleSpring", "IntSpring"]

gitSourceBranch = "main"

[docusaurus]
url = "https://ambergracesoftware.com"
baseUrl = "/dec"
tagline = "A reactive UI library for Roblox"

[navbar]
title = ""

[navbar.logo]
alt = "Dec"
src = "LogoNoBG.png"

[home]
enabled = true
includeReadme = false