[[classOrder]]
section = "Core"
classes = ["Dec", "VirtualInstance", "Root"]

[[classOrder]]
section = "Observables"
classes = ["Observable", "State", "Record", "Dict", "Stopwatch", "Timer",
    "Alpha", "Eased", "Spring", "AngleSpring", "IntSpring"]

gitSourceBranch = "main"

[docusaurus]
url = "https://dec.ambergracesoftware.com"
baseUrl = "/"
tagline = "A reactive UI library for Roblox"

[navbar]
title = ""

[navbar.logo]
alt = "Dec"
src = "logo.png"

[home]
enabled = true
includeReadme = false