name: Analyze Source Code

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup aftman toolchain
        uses: ok-nick/setup-aftman@v0.3.0
      - name: Generate Rojo Sourcemap
        run: rojo sourcemap --output sourcemap.json
      - name: Download latest Roblox API types
        run: |
          curl \
            -H 'Accept: application/vnd.github.v3.raw' \
            -O \
            -L 'https://api.github.com/repos/JohnnyMorganz/luau-lsp/contents/scripts/globalTypes.d.lua'
      - name: Verify type safety with luau-lsp
        run: |
          luau-lsp analyze tests src --sourcemap=sourcemap.json \
            --definitions=globalTypes.d.lua \
            --definitions=testez.d.luau
      - name: Verify code integrity with selene 
        run: selene src tests