name: Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup aftman toolchain
        uses: ok-nick/setup-aftman@v0.3.0
      - name: Verify Proof-Of-Testing with current source file structure
        run: lune ValidateProofOfTesting.luau